#!/bin/bash
# Test suite for templates/.githooks/commit-msg
HOOK="./templates/.githooks/commit-msg"
PASS=0; FAIL=0; TOTAL=0

run_test() {
    local desc="$1" input="$2" expect="$3"
    TOTAL=$((TOTAL+1))
    tmpfile=$(mktemp)
    echo "$input" > "$tmpfile"
    if "$HOOK" "$tmpfile" >/dev/null 2>&1; then result=0; else result=1; fi
    rm -f "$tmpfile"
    if [ "$result" -eq "$expect" ]; then
        PASS=$((PASS+1))
        echo "  ✓ $desc"
    else
        FAIL=$((FAIL+1))
        echo "  ✗ $desc (expected exit $expect, got $result)"
    fi
}

echo "Testing commit-msg hook..."
echo ""

# Should PASS (exit 0)
run_test "basic feat" "✨ feat: add feature" 0
run_test "feat with scope" "✨ feat(installer): add gum menu" 0
run_test "breaking change" "✨ feat!: rename workspace" 0
run_test "scope and breaking" "✨ feat(api)!: change endpoint" 0
run_test "ci type" "🔄 ci: add release workflow" 0
run_test "revert type" "↩️ revert: undo broken rule" 0
run_test "plan type" "📋 plan: update auth blueprint" 0
run_test "fix type" "🐛 fix: resolve validation" 0
run_test "docs type" "📚 docs: update README" 0
run_test "test type" "🧪 test: add coverage" 0
run_test "hotfix type" "🩹 hotfix: urgent fix" 0
run_test "merge type" "🔀 merge: merge staging" 0
run_test "refactor type" "♻️ refactor: clean up code" 0
run_test "style type" "💄 style: fix indentation" 0
run_test "perf type" "⚡ perf: optimize query" 0
run_test "build type" "🔧 build: update makefile" 0
run_test "chore type" "🧹 chore: update deps" 0
run_test "security type" "🔒 security: fix xss" 0
run_test "migration type" "🗃️ migration: add users table" 0
run_test "deps type" "📦 deps: update packages" 0
run_test "deploy type" "🚀 deploy: update ci config" 0
run_test "remove type" "🔥 remove: drop legacy code" 0

# Should FAIL (exit 1)
run_test "missing emoji" "feat: no emoji" 1
run_test "unknown type" "✨ unknown: bad type" 1
run_test "empty description" "✨ feat:" 1
run_test "no space after colon" "✨ feat:nospace" 1
run_test "AI signature Co-Authored-By" "✨ feat: something
Co-Authored-By: Claude <noreply@anthropic.com>" 1
run_test "AI signature Generated by" "✨ feat: something
Generated by Claude" 1

echo ""
echo "Results: $PASS/$TOTAL passed, $FAIL failed"
[ "$FAIL" -eq 0 ] && exit 0 || exit 1
