package audit

import (
	"testing"
)

func TestValidateCommitMessage_PassCases(t *testing.T) {
	pass := []string{
		"✨ feat: add new feature",
		"✨ feat(scope): add scoped feature",
		"💥 feat!: breaking change",
		"🔄 ci: update workflow",
		"↩️ revert: undo last commit",
		"📋 plan: update plan file",
		"🐛 fix: resolve bug",
		"📚 docs: update readme",
		"♻️ refactor: restructure code",
		"🧪 test: add tests",
		"⚡ perf: improve performance",
		"💄 style: format code",
		"🔧 build: update build config",
		"🧹 chore: maintenance",
		"🗃️ migration: add migration",
		"🔥 remove: delete old code",
		"🔒 security: fix vulnerability",
		"📦 deps: update dependencies",
		"🩹 hotfix: urgent fix",
		"🔀 merge: merge branches",
		"🚀 deploy: update deployment",
		"✨ feat(auth/login): scoped with slash",
		"✨ feat(my-scope)!: scoped breaking",
	}

	for _, msg := range pass {
		valid, errMsg := ValidateCommitMessage(msg)
		if !valid {
			t.Errorf("expected PASS for %q, got FAIL: %s", msg, errMsg)
		}
	}
}

func TestValidateCommitMessage_FailCases(t *testing.T) {
	fail := []struct {
		msg    string
		reason string
	}{
		{"feat: no emoji", "missing emoji prefix"},
		{"✨ unknown: bad type", "unknown type"},
		{"✨ feat:", "empty description"},
		{"", "empty message"},
		{"just some random text", "no format"},
	}

	for _, tc := range fail {
		valid, _ := ValidateCommitMessage(tc.msg)
		if valid {
			t.Errorf("expected FAIL for %q (%s), got PASS", tc.msg, tc.reason)
		}
	}
}

func TestValidateCommitMessage_AISignatureBlocked(t *testing.T) {
	sigs := []string{
		"✨ feat: add feature\n\nCo-Authored-By: Claude <noreply@anthropic.com>",
		"✨ feat: add feature Generated by AI",
		"✨ feat: add feature Generated by Claude",
	}

	for _, msg := range sigs {
		valid, errMsg := ValidateCommitMessage(msg)
		if valid {
			t.Errorf("expected BLOCK for AI signature in %q, got PASS", msg)
		}
		if errMsg == "" {
			t.Errorf("expected error message for AI signature in %q", msg)
		}
	}
}

func TestDetectBreakingChange(t *testing.T) {
	tests := []struct {
		body     string
		expected bool
	}{
		{"Some body text\n\nBREAKING CHANGE: removed API endpoint", true},
		{"BREAKING CHANGE: everything changed", true},
		{"Some normal body text", false},
		{"", false},
		{"This is a breaking change but not the footer", false},
	}

	for _, tc := range tests {
		got := DetectBreakingChange(tc.body)
		if got != tc.expected {
			t.Errorf("DetectBreakingChange(%q) = %v, want %v", tc.body, got, tc.expected)
		}
	}
}

func TestCommitRegex_MatchesExpectedFormat(t *testing.T) {
	// Verify the regex pattern itself
	if !reCommitMsg.MatchString("✨ feat: description") {
		t.Error("regex should match basic format")
	}
	if !reCommitMsg.MatchString("✨ feat(scope): description") {
		t.Error("regex should match scoped format")
	}
	if !reCommitMsg.MatchString("✨ feat!: breaking description") {
		t.Error("regex should match breaking format")
	}
	if !reCommitMsg.MatchString("✨ feat(scope)!: scoped breaking") {
		t.Error("regex should match scoped breaking format")
	}
	if reCommitMsg.MatchString("feat: no emoji") {
		t.Error("regex should not match without emoji prefix")
	}
}
