package audit

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestLoadBlueprintConfig_Default(t *testing.T) {
	// When no config file exists, should return default
	origDir, _ := os.Getwd()
	tmpDir := t.TempDir()
	os.Chdir(tmpDir)
	defer os.Chdir(origDir)

	cfg := LoadBlueprintConfig()
	if cfg.StagingBranch != "staging" {
		t.Errorf("expected default staging_branch 'staging', got %q", cfg.StagingBranch)
	}
}

func TestLoadBlueprintConfig_FromFile(t *testing.T) {
	origDir, _ := os.Getwd()
	tmpDir := t.TempDir()
	os.Chdir(tmpDir)
	defer os.Chdir(origDir)

	// Create config
	os.MkdirAll("blueprint", 0755)
	os.WriteFile("blueprint/.config.yml", []byte("staging_branch: staging\n"), 0644)

	cfg := LoadBlueprintConfig()
	if cfg.StagingBranch != "staging" {
		t.Errorf("expected staging_branch 'staging', got %q", cfg.StagingBranch)
	}
}

func TestPlanningReferencesUseBlueprintDir(t *testing.T) {
	// Verify that todo/md regexes use blueprint/ not .planning/
	if rePlanningTodo.MatchString(".planning/001-todo.md") {
		t.Error("rePlanningTodo should NOT match .planning/ paths")
	}
	if !rePlanningTodo.MatchString("blueprint/001-feat-test-todo.md") {
		t.Error("rePlanningTodo should match blueprint/ paths")
	}

	if rePlanningMd.MatchString(".planning/test.md") {
		t.Error("rePlanningMd should NOT match .planning/ paths")
	}
	if !rePlanningMd.MatchString("blueprint/test.md") {
		t.Error("rePlanningMd should match blueprint/ paths")
	}
}

func TestBacklogCLIBlocksManualParsing(t *testing.T) {
	// Verify backlog patterns use blueprint/ not .planning/
	if reBacklogGrep.MatchString("grep foo .planning/backlog") {
		t.Error("reBacklogGrep should NOT match .planning/ paths")
	}
	if !reBacklogGrep.MatchString("grep foo blueprint/backlog") {
		t.Error("reBacklogGrep should match blueprint/ paths")
	}
}

func TestAISignaturesBlocked(t *testing.T) {
	patterns := []string{
		"Co-Authored-By: Claude",
		"Generated by AI",
		"Generated by Claude",
	}
	for _, p := range patterns {
		if !reAISig.MatchString(p) {
			t.Errorf("reAISig should match %q", p)
		}
	}
}

func TestMigrateFreshBlocked(t *testing.T) {
	if !reMigrateFresh.MatchString("php artisan migrate:fresh") {
		t.Error("reMigrateFresh should match migrate:fresh")
	}
	if reMigrateFresh.MatchString("php artisan migrate") {
		t.Error("reMigrateFresh should NOT match plain migrate")
	}
}

func TestGitPushMainBlocked(t *testing.T) {
	if !reGitPushMain.MatchString("git push origin main") {
		t.Error("reGitPushMain should match 'git push origin main'")
	}
	if reGitPushMain.MatchString("git push origin feature/test") {
		t.Error("reGitPushMain should NOT match feature branch push")
	}
}

func TestRule7ConfigIntegration(t *testing.T) {
	// Create a temp directory with a config file
	origDir, _ := os.Getwd()
	tmpDir := t.TempDir()
	os.Chdir(tmpDir)
	defer os.Chdir(origDir)

	// Create config with custom staging branch
	os.MkdirAll("blueprint", 0755)
	os.WriteFile("blueprint/.config.yml", []byte("staging_branch: develop\n"), 0644)

	cfg := LoadBlueprintConfig()
	if cfg.StagingBranch != "develop" {
		t.Errorf("expected staging_branch 'develop', got %q", cfg.StagingBranch)
	}
}

func TestSessionState(t *testing.T) {
	state := NewSessionState("test-session-" + filepath.Base(t.TempDir()))
	defer os.RemoveAll(state.Dir)

	// Touch and Exists
	if state.Exists("marker") {
		t.Error("marker should not exist yet")
	}
	state.Touch("marker")
	if !state.Exists("marker") {
		t.Error("marker should exist after Touch")
	}

	// WriteText and ReadText
	state.WriteText("data", "hello world")
	if got := state.ReadText("data"); got != "hello world" {
		t.Errorf("ReadText got %q, want 'hello world'", got)
	}

	// IncrInt
	if got := state.IncrInt("counter"); got != 1 {
		t.Errorf("IncrInt first call got %d, want 1", got)
	}
	if got := state.IncrInt("counter"); got != 2 {
		t.Errorf("IncrInt second call got %d, want 2", got)
	}

	// AppendLine
	state.AppendLine("lines", "first")
	state.AppendLine("lines", "second")
	text := state.ReadText("lines")
	if !strings.Contains(text, "first") || !strings.Contains(text, "second") {
		t.Errorf("AppendLine content = %q, should contain both lines", text)
	}
}

func TestAllowedCommitTypes(t *testing.T) {
	expected := []string{
		"feat", "fix", "docs", "refactor", "test", "perf", "style",
		"build", "chore", "ci", "revert", "plan", "migration",
		"remove", "security", "deps", "hotfix", "merge", "deploy",
	}
	for _, typ := range expected {
		if _, ok := AllowedCommitTypes[typ]; !ok {
			t.Errorf("AllowedCommitTypes missing type %q", typ)
		}
	}
	if _, ok := AllowedCommitTypes["ci"]; !ok {
		t.Error("AllowedCommitTypes should include 'ci'")
	}
	if _, ok := AllowedCommitTypes["revert"]; !ok {
		t.Error("AllowedCommitTypes should include 'revert'")
	}
}
